# Generated by Django 3.1.5 on 2021-01-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maryam', '0002_auto_20210127_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
