# Generated by Django 2.2.13 on 2021-01-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maryam', '0003_auto_20210127_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
