# Generated by Django 2.2.13 on 2021-01-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maryam', '0004_auto_20210127_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
