# Generated by Django 2.2.13 on 2021-01-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maryam', '0005_auto_20210127_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel_id',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
