# Generated by Django 2.2.13 on 2021-01-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maryam', '0007_auto_20210127_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', help_text='Enter your Password for site', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel_id',
            field=models.CharField(default='', help_text='Enter your telegram id for site', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', help_text='Enter your Username for site', max_length=255, null=True),
        ),
    ]
