# Generated by Django 2.2.13 on 2021-01-28 21:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('maryam', '0009_auto_20210128_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', help_text='تلفن خود را وارد کنید. شماره تلفن شما برای بازیابی رمز عبور استفاده می شودد', max_length=11, null=True, region=None),
        ),
    ]
