# Generated by Django 2.2.13 on 2021-01-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maryam', '0010_auto_20210128_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default='', help_text='تلفن خود را وارد کنید. شماره تلفن شما برای بازیابی رمز عبور استفاده می شودد', max_length=11, null=True),
        ),
    ]
