# Generated by Django 2.2.13 on 2021-01-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maryam', '0011_auto_20210128_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loggedin',
            field=models.IntegerField(default=0, help_text='login is true or false', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', help_text='تلفن خود را وارد کنید. شماره تلفن شما برای بازیابی رمز عبور استفاده می شود', max_length=11, null=True),
        ),
    ]
