# Generated by Django 2.2.13 on 2021-02-21 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maryam', '0012_auto_20210129_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hejab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='نام نمایشی کالا را وارد کنید', max_length=250, null=True)),
                ('text', models.TextField(default='', help_text='توضیحات کالا را وارد کنید', max_length=250, null=True)),
                ('img', models.CharField(default='', help_text='آدرس فایل آپلود شده در پیکوفایل را وارد کنید', max_length=250, null=True)),
                ('amount', models.CharField(default='', help_text='آدرس فایل آپلود شده در پیکوفایل را وارد کنید', max_length=250, null=True)),
                ('num', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kharazi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='نام نمایشی کالا را وارد کنید', max_length=250, null=True)),
                ('text', models.TextField(default='', help_text='توضیحات کالا را وارد کنید', max_length=250, null=True)),
                ('img', models.CharField(default='', help_text='آدرس فایل آپلود شده در پیکوفایل را وارد کنید', max_length=250, null=True)),
                ('amount', models.CharField(default='', help_text='آدرس فایل آپلود شده در پیکوفایل را وارد کنید', max_length=250, null=True)),
                ('num', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Parcheh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='نام نمایشی کالا را وارد کنید', max_length=250, null=True)),
                ('text', models.TextField(default='', help_text='توضیحات کالا را وارد کنید', max_length=250, null=True)),
                ('img', models.CharField(default='', help_text='آدرس فایل آپلود شده در پیکوفایل را وارد کنید', max_length=250, null=True)),
                ('amount', models.CharField(default='', help_text='آدرس فایل آپلود شده در پیکوفایل را وارد کنید', max_length=250, null=True)),
                ('num', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pooshak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='نام نمایشی کالا را وارد کنید', max_length=250, null=True)),
                ('text', models.TextField(default='', help_text='توضیحات کالا را وارد کنید', max_length=250, null=True)),
                ('img', models.CharField(default='', help_text='آدرس فایل آپلود شده در پیکوفایل را وارد کنید', max_length=250, null=True)),
                ('amount', models.CharField(default='', help_text='آدرس فایل آپلود شده در پیکوفایل را وارد کنید', max_length=250, null=True)),
                ('num', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='loggedin',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', help_text='از آدرس برای ارسال کالا به درب منزل استفاده می شود.', max_length=500000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='post_code',
            field=models.CharField(default='', help_text='از کد پستی برای ارسال کالا به درب منزل استفاده می شود', max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', help_text='رمز خود را وارد کنید. این رمز برای ورود شما به سایت اسفاده می شود', max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel_id',
            field=models.CharField(default='', help_text='آی دی تلگرام خود را وارد کنید. این آی دی برای سفارشات شما استفاده می شود', max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', help_text='نام کاربری خود را وارد کنید. این نام کاربری برای ورود شما استفاده می شود', max_length=500000, null=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('amount', models.CharField(default='', max_length=255)),
                ('kala_address', models.CharField(default='', max_length=255)),
                ('img', models.CharField(default='', max_length=255)),
                ('num', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maryam.User')),
            ],
        ),
    ]
