# Generated by Django 2.2.13 on 2021-02-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maryam', '0013_auto_20210221_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='group',
            field=models.CharField(default='', max_length=255),
        ),
    ]
