# Generated by Django 2.2.13 on 2021-02-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maryam', '0014_cart_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='this_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
